name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Extract version from tag (remove 'v')
      id: get_version
      run: |
        VERSION=${GITHUB_REF##*/}
        VERSION=$(echo $VERSION | sed 's/^v//')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build --build-arg FOLIA_VERSION=$VERSION -t mixels/folia:$VERSION .

    - name: Save Docker image for test job
      run: docker save endkind/folia:$VERSION > image.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar

  push:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image

    - name: Extract version from tag (remove 'v')
      id: get_version
      run: |
        VERSION=${GITHUB_REF##*/}
        VERSION=$(echo $VERSION | sed 's/^v//')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Load Docker image
      run: docker load < image.tar

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push the Docker image
      run: docker push mixels/folia-for-gsa-windows:$VERSION

  create-issue-on-failure:
    runs-on: ubuntu-latest
    needs:
      - build
      - push
    if: failure()
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Replace placeholders in issue template
        env:
          SHA: ${{ github.sha }}
          WORKFLOW_NAME: ${{ github.workflow }}
          JOB_NAME: ${{ github.job }}
          RUN_ID: ${{ github.run_id }}
          LOGS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          TAG=${GITHUB_REF##*/}
          echo "TAG=$TAG" >> $GITHUB_ENV

          sed -i "s|{{sha}}|$SHA|g" .github/ISSUE_TEMPLATE.md
          sed -i "s|{{tag}}|$TAG|g" .github/ISSUE_TEMPLATE.md
          sed -i "s|{{workflow_name}}|$WORKFLOW_NAME|g" .github/ISSUE_TEMPLATE.md
          sed -i "s|{{job_name}}|$JOB_NAME|g" .github/ISSUE_TEMPLATE.md
          sed -i "s|{{run_id}}|$RUN_ID|g" .github/ISSUE_TEMPLATE.md
          sed -i "s|{{logs_url}}|$LOGS_URL|g" .github/ISSUE_TEMPLATE.md

      - name: Create a GitHub Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md

